dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-Console-release.o ./tango/io/Console.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-FilePath-release.o ./tango/io/FilePath.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-FileScan-release.o ./tango/io/FileScan.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-FileSystem-release.o ./tango/io/FileSystem.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-Path-release.o ./tango/io/Path.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-Stdout-release.o ./tango/io/Stdout.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-UnicodeFile-release.o ./tango/io/UnicodeFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-Array-release.o ./tango/io/device/Array.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-BitBucket-release.o ./tango/io/device/BitBucket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-Conduit-release.o ./tango/io/device/Conduit.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-Device-release.o ./tango/io/device/Device.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-File-release.o ./tango/io/device/File.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-FileMap-release.o ./tango/io/device/FileMap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-SerialPort-release.o ./tango/io/device/SerialPort.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-TempFile-release.o ./tango/io/device/TempFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-device-ThreadPipe-release.o ./tango/io/device/ThreadPipe.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-model-IConduit-release.o ./tango/io/model/IConduit.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-model-IFile-release.o ./tango/io/model/IFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-AbstractSelector-release.o ./tango/io/selector/AbstractSelector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-EpollSelector-release.o ./tango/io/selector/EpollSelector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-PollSelector-release.o ./tango/io/selector/PollSelector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-Selector-release.o ./tango/io/selector/Selector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-SelectorException-release.o ./tango/io/selector/SelectorException.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-SelectSelector-release.o ./tango/io/selector/SelectSelector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-selector-model-ISelector-release.o ./tango/io/selector/model/ISelector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Buffered-release.o ./tango/io/stream/Buffered.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Bzip-release.o ./tango/io/stream/Bzip.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Data-release.o ./tango/io/stream/Data.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-DataFile-release.o ./tango/io/stream/DataFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Delimiters-release.o ./tango/io/stream/Delimiters.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Digester-release.o ./tango/io/stream/Digester.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Endian-release.o ./tango/io/stream/Endian.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Format-release.o ./tango/io/stream/Format.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Greedy-release.o ./tango/io/stream/Greedy.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Iterator-release.o ./tango/io/stream/Iterator.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Lines-release.o ./tango/io/stream/Lines.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Map-release.o ./tango/io/stream/Map.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Patterns-release.o ./tango/io/stream/Patterns.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Quotes-release.o ./tango/io/stream/Quotes.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Snoop-release.o ./tango/io/stream/Snoop.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Text-release.o ./tango/io/stream/Text.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-TextFile-release.o ./tango/io/stream/TextFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Typed-release.o ./tango/io/stream/Typed.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Utf-release.o ./tango/io/stream/Utf.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-stream-Zlib-release.o ./tango/io/stream/Zlib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-FileFolder-release.o ./tango/io/vfs/FileFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-FtpFolder-release.o ./tango/io/vfs/FtpFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-LinkedFolder-release.o ./tango/io/vfs/LinkedFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-VirtualFolder-release.o ./tango/io/vfs/VirtualFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-ZipFolder-release.o ./tango/io/vfs/ZipFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-io-vfs-model-Vfs-release.o ./tango/io/vfs/model/Vfs.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-Bessel-release.o ./tango/math/Bessel.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-BigInt-release.o ./tango/math/BigInt.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-Bracket-release.o ./tango/math/Bracket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-Elliptic-release.o ./tango/math/Elliptic.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-ErrorFunction-release.o ./tango/math/ErrorFunction.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-GammaFunction-release.o ./tango/math/GammaFunction.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-IEEE-release.o ./tango/math/IEEE.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-Math-release.o ./tango/math/Math.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-Probability-release.o ./tango/math/Probability.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-internal-BignumNoAsm-release.o ./tango/math/internal/BignumNoAsm.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-internal-BignumX86-release.o ./tango/math/internal/BignumX86.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-internal-BiguintCore-release.o ./tango/math/internal/BiguintCore.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-ExpSource-release.o ./tango/math/random/ExpSource.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-Kiss-release.o ./tango/math/random/Kiss.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-NormalSource-release.o ./tango/math/random/NormalSource.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-Random-release.o ./tango/math/random/Random.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-Twister-release.o ./tango/math/random/Twister.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-Ziggurat-release.o ./tango/math/random/Ziggurat.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-ArraySource-release.o ./tango/math/random/engines/ArraySource.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-CMWC-release.o ./tango/math/random/engines/CMWC.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-KISS-release.o ./tango/math/random/engines/KISS.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-KissCmwc-release.o ./tango/math/random/engines/KissCmwc.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-Sync-release.o ./tango/math/random/engines/Sync.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-Twister-release.o ./tango/math/random/engines/Twister.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-math-random-engines-URandom-release.o ./tango/math/random/engines/URandom.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-InternetAddress-release.o ./tango/net/InternetAddress.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-Uri-release.o ./tango/net/Uri.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-Berkeley-release.o ./tango/net/device/Berkeley.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-Datagram-release.o ./tango/net/device/Datagram.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-LocalSocket-release.o ./tango/net/device/LocalSocket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-Multicast-release.o ./tango/net/device/Multicast.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-Socket-release.o ./tango/net/device/Socket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-device-SSLSocket-release.o ./tango/net/device/SSLSocket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-ftp-FtpClient-release.o ./tango/net/ftp/FtpClient.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-ftp-Telnet-release.o ./tango/net/ftp/Telnet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-ChunkStream-release.o ./tango/net/http/ChunkStream.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpClient-release.o ./tango/net/http/HttpClient.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpConst-release.o ./tango/net/http/HttpConst.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpCookies-release.o ./tango/net/http/HttpCookies.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpGet-release.o ./tango/net/http/HttpGet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpHeaders-release.o ./tango/net/http/HttpHeaders.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpParams-release.o ./tango/net/http/HttpParams.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpPost-release.o ./tango/net/http/HttpPost.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpStack-release.o ./tango/net/http/HttpStack.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpTokens-release.o ./tango/net/http/HttpTokens.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-HttpTriplet-release.o ./tango/net/http/HttpTriplet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-http-model-HttpParamsView-release.o ./tango/net/http/model/HttpParamsView.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-model-UriView-release.o ./tango/net/model/UriView.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-util-MemCache-release.o ./tango/net/util/MemCache.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-util-PKI-release.o ./tango/net/util/PKI.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-net-util-c-OpenSSL-release.o ./tango/net/util/c/OpenSSL.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-complex-release.o ./tango/stdc/complex.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-config-release.o ./tango/stdc/config.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-ctype-release.o ./tango/stdc/ctype.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-errno-release.o ./tango/stdc/errno.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-fenv-release.o ./tango/stdc/fenv.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-inttypes-release.o ./tango/stdc/inttypes.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-limits-release.o ./tango/stdc/limits.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-locale-release.o ./tango/stdc/locale.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-math-release.o ./tango/stdc/math.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-signal-release.o ./tango/stdc/signal.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stdarg-release.o ./tango/stdc/stdarg.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stddef-release.o ./tango/stdc/stddef.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stdint-release.o ./tango/stdc/stdint.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stdio-release.o ./tango/stdc/stdio.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stdlib-release.o ./tango/stdc/stdlib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-string-release.o ./tango/stdc/string.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-stringz-release.o ./tango/stdc/stringz.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-tgmath-release.o ./tango/stdc/tgmath.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-time-release.o ./tango/stdc/time.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-wctype-release.o ./tango/stdc/wctype.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-config-release.o ./tango/stdc/posix/config.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-dirent-release.o ./tango/stdc/posix/dirent.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-dlfcn-release.o ./tango/stdc/posix/dlfcn.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-fcntl-release.o ./tango/stdc/posix/fcntl.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-grp-release.o ./tango/stdc/posix/grp.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-inttypes-release.o ./tango/stdc/posix/inttypes.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-langinfo-release.o ./tango/stdc/posix/langinfo.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-poll-release.o ./tango/stdc/posix/poll.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-pthread-release.o ./tango/stdc/posix/pthread.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-pwd-release.o ./tango/stdc/posix/pwd.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sched-release.o ./tango/stdc/posix/sched.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-semaphore-release.o ./tango/stdc/posix/semaphore.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-setjmp-release.o ./tango/stdc/posix/setjmp.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-signal-release.o ./tango/stdc/posix/signal.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-stdio-release.o ./tango/stdc/posix/stdio.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-stdlib-release.o ./tango/stdc/posix/stdlib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-termios-release.o ./tango/stdc/posix/termios.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-time-release.o ./tango/stdc/posix/time.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-ucontext-release.o ./tango/stdc/posix/ucontext.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-unistd-release.o ./tango/stdc/posix/unistd.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-utime-release.o ./tango/stdc/posix/utime.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-arpa-inet-release.o ./tango/stdc/posix/arpa/inet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-net-if_-release.o ./tango/stdc/posix/net/if_.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-netinet-in_-release.o ./tango/stdc/posix/netinet/in_.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-netinet-tcp-release.o ./tango/stdc/posix/netinet/tcp.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-ipc-release.o ./tango/stdc/posix/sys/ipc.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-mman-release.o ./tango/stdc/posix/sys/mman.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-select-release.o ./tango/stdc/posix/sys/select.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-shm-release.o ./tango/stdc/posix/sys/shm.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-socket-release.o ./tango/stdc/posix/sys/socket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-stat-release.o ./tango/stdc/posix/sys/stat.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-statvfs-release.o ./tango/stdc/posix/sys/statvfs.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-time-release.o ./tango/stdc/posix/sys/time.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-types-release.o ./tango/stdc/posix/sys/types.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-uio-release.o ./tango/stdc/posix/sys/uio.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-utsname-release.o ./tango/stdc/posix/sys/utsname.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-stdc-posix-sys-wait-release.o ./tango/stdc/posix/sys/wait.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-Common-release.o ./tango/sys/Common.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-Environment-release.o ./tango/sys/Environment.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-HomeFolder-release.o ./tango/sys/HomeFolder.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-Pipe-release.o ./tango/sys/Pipe.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-Process-release.o ./tango/sys/Process.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-SharedLib-release.o ./tango/sys/SharedLib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-consts-errno-release.o ./tango/sys/consts/errno.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-consts-fcntl-release.o ./tango/sys/consts/fcntl.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-consts-socket-release.o ./tango/sys/consts/socket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-consts-sysctl-release.o ./tango/sys/consts/sysctl.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-consts-unistd-release.o ./tango/sys/consts/unistd.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-darwin-release.o ./tango/sys/darwin/darwin.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-errno-release.o ./tango/sys/darwin/consts/errno.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-fcntl-release.o ./tango/sys/darwin/consts/fcntl.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-machine-release.o ./tango/sys/darwin/consts/machine.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-socket-release.o ./tango/sys/darwin/consts/socket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-sysctl-release.o ./tango/sys/darwin/consts/sysctl.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-sys-darwin-consts-unistd-release.o ./tango/sys/darwin/consts/unistd.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Arguments-release.o ./tango/text/Arguments.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Ascii-release.o ./tango/text/Ascii.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Regex-release.o ./tango/text/Regex.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Search-release.o ./tango/text/Search.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Text-release.o ./tango/text/Text.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Unicode-release.o ./tango/text/Unicode.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-UnicodeData-release.o ./tango/text/UnicodeData.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-Util-release.o ./tango/text/Util.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-DateTime-release.o ./tango/text/convert/DateTime.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-Float-release.o ./tango/text/convert/Float.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-Format-release.o ./tango/text/convert/Format.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-Integer-release.o ./tango/text/convert/Integer.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-Layout-release.o ./tango/text/convert/Layout.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-TimeStamp-release.o ./tango/text/convert/TimeStamp.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-UnicodeBom-release.o ./tango/text/convert/UnicodeBom.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-convert-Utf-release.o ./tango/text/convert/Utf.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-json-Json-release.o ./tango/text/json/Json.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-json-JsonEscape-release.o ./tango/text/json/JsonEscape.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-json-JsonParser-release.o ./tango/text/json/JsonParser.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Collation-release.o ./tango/text/locale/Collation.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Convert-release.o ./tango/text/locale/Convert.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Core-release.o ./tango/text/locale/Core.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Data-release.o ./tango/text/locale/Data.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Locale-release.o ./tango/text/locale/Locale.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Parse-release.o ./tango/text/locale/Parse.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Posix-release.o ./tango/text/locale/Posix.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-locale-Win32-release.o ./tango/text/locale/Win32.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-DocEntity-release.o ./tango/text/xml/DocEntity.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-DocPrinter-release.o ./tango/text/xml/DocPrinter.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-DocTester-release.o ./tango/text/xml/DocTester.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-Document-release.o ./tango/text/xml/Document.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-PullParser-release.o ./tango/text/xml/PullParser.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-text-xml-SaxParser-release.o ./tango/text/xml/SaxParser.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-Clock-release.o ./tango/time/Clock.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-ISO8601-release.o ./tango/time/ISO8601.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-StopWatch-release.o ./tango/time/StopWatch.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-Time-release.o ./tango/time/Time.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-WallClock-release.o ./tango/time/WallClock.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Calendar-release.o ./tango/time/chrono/Calendar.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Gregorian-release.o ./tango/time/chrono/Gregorian.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-GregorianBased-release.o ./tango/time/chrono/GregorianBased.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Hebrew-release.o ./tango/time/chrono/Hebrew.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Hijri-release.o ./tango/time/chrono/Hijri.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Japanese-release.o ./tango/time/chrono/Japanese.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Korean-release.o ./tango/time/chrono/Korean.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-Taiwan-release.o ./tango/time/chrono/Taiwan.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-time-chrono-ThaiBuddhist-release.o ./tango/time/chrono/ThaiBuddhist.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-Convert-release.o ./tango/util/Convert.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-MinMax-release.o ./tango/util/MinMax.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-AES-release.o ./tango/util/cipher/AES.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-Blowfish-release.o ./tango/util/cipher/Blowfish.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-ChaCha-release.o ./tango/util/cipher/ChaCha.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-Cipher-release.o ./tango/util/cipher/Cipher.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-RC4-release.o ./tango/util/cipher/RC4.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-RC6-release.o ./tango/util/cipher/RC6.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-Salsa20-release.o ./tango/util/cipher/Salsa20.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-TEA-release.o ./tango/util/cipher/TEA.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-cipher-XTEA-release.o ./tango/util/cipher/XTEA.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-compress-Zip-release.o ./tango/util/compress/Zip.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-compress-c-bzlib-release.o ./tango/util/compress/c/bzlib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-compress-c-zlib-release.o ./tango/util/compress/c/zlib.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-CircularList-release.o ./tango/util/container/CircularList.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-Clink-release.o ./tango/util/container/Clink.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-Container-release.o ./tango/util/container/Container.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-HashMap-release.o ./tango/util/container/HashMap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-HashSet-release.o ./tango/util/container/HashSet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-LinkedList-release.o ./tango/util/container/LinkedList.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-RedBlack-release.o ./tango/util/container/RedBlack.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-Slink-release.o ./tango/util/container/Slink.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-SortedMap-release.o ./tango/util/container/SortedMap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-model-IContainer-release.o ./tango/util/container/model/IContainer.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-BitSet-release.o ./tango/util/container/more/BitSet.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-CacheMap-release.o ./tango/util/container/more/CacheMap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-HashFile-release.o ./tango/util/container/more/HashFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-Heap-release.o ./tango/util/container/more/Heap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-Stack-release.o ./tango/util/container/more/Stack.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-StackMap-release.o ./tango/util/container/more/StackMap.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-container-more-Vector-release.o ./tango/util/container/more/Vector.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Crc32-release.o ./tango/util/digest/Crc32.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Digest-release.o ./tango/util/digest/Digest.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Md2-release.o ./tango/util/digest/Md2.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Md4-release.o ./tango/util/digest/Md4.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Md5-release.o ./tango/util/digest/Md5.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-MerkleDamgard-release.o ./tango/util/digest/MerkleDamgard.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Ripemd128-release.o ./tango/util/digest/Ripemd128.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Ripemd160-release.o ./tango/util/digest/Ripemd160.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Ripemd256-release.o ./tango/util/digest/Ripemd256.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Ripemd320-release.o ./tango/util/digest/Ripemd320.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Sha0-release.o ./tango/util/digest/Sha0.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Sha01-release.o ./tango/util/digest/Sha01.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Sha1-release.o ./tango/util/digest/Sha1.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Sha256-release.o ./tango/util/digest/Sha256.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Sha512-release.o ./tango/util/digest/Sha512.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Tiger-release.o ./tango/util/digest/Tiger.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-digest-Whirlpool-release.o ./tango/util/digest/Whirlpool.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-encode-Base16-release.o ./tango/util/encode/Base16.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-encode-Base32-release.o ./tango/util/encode/Base32.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-encode-Base64-release.o ./tango/util/encode/Base64.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendConsole-release.o ./tango/util/log/AppendConsole.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendFile-release.o ./tango/util/log/AppendFile.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendFiles-release.o ./tango/util/log/AppendFiles.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendMail-release.o ./tango/util/log/AppendMail.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendSocket-release.o ./tango/util/log/AppendSocket.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-AppendSyslog-release.o ./tango/util/log/AppendSyslog.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-Config-release.o ./tango/util/log/Config.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-ConfigProps-release.o ./tango/util/log/ConfigProps.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-LayoutChainsaw-release.o ./tango/util/log/LayoutChainsaw.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-LayoutDate-release.o ./tango/util/log/LayoutDate.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-Log-release.o ./tango/util/log/Log.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-Trace-release.o ./tango/util/log/Trace.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-log-model-ILogger-release.o ./tango/util/log/model/ILogger.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-uuid-NamespaceGenV3-release.o ./tango/util/uuid/NamespaceGenV3.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-uuid-NamespaceGenV5-release.o ./tango/util/uuid/NamespaceGenV5.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-uuid-RandomGen-release.o ./tango/util/uuid/RandomGen.d 
dmd -c -I./tango/core -I. -I./tango/core/vendor -release -oftango-util-uuid-Uuid-release.o ./tango/util/uuid/Uuid.d 
